version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: c0nygre
      MYSQL_DATABASE: conygre
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./financial.sql:/docker-entrypoint-initdb.d/financial.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/conygre?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: c0nygre

volumes:
  mysql-data:
